site_name: TrustyAI-Python
docs_dir: src
site_dir: docs
nav:
  - Home: index.md
  - Counterfactuals: counterfactuals.md
theme:
  name: material
  font:
    code: JetBrains Mono
    text: Overpass
  palette:
    primary: light blue
    accent: orange
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js